### ISSUE TITLE
Add second applicant filed

### ISSUE THREAD

**Issue by MargoWM** [CodeForPoznan/alinka-electron#107]
**Bussiness context**

Usually child has two parents. So we need insert additional inputs for second parent's name and address.
AC:
* Add input for second parent: `Imię i nazwisko drugiego wnioskodawcy`, `adres drugiego wnioskodawcy`, `miejscowość drugiego wnioskodawcy`, `kod pocztowy drugiego wnioskodawcy`

**Comment by Rafalkufel** [comment]
Hi!, Should the second applicant inputs be required? Of cource child can have only one parrent/applicant. So at the first glance we don't need require second parents inputs filled. But... If user fill some of inputs eg. `firstName`. The rest inputs should become required. Very fancy logic is hidden there... :)

**Comment by paulinatar** [comment]
So, maybe on first view should be  visible  required inputs for first applicant (name surname adreess), and all inputs about second applicant included first name ect. (if second applicant is not required)  should be hidden and only open (all box for second applicant) after click ?

**Comment by Rafalkufel** [comment]
Yes, I think it's going to work. But maybe on first iteration we can focus only on adding that second parent inputs and allow them to be empty, and solve that _required_ issues later in some other ticket?
