### ISSUE TITLE
Create summary component.

### ISSUE THREAD

**Issue by Rafalkufel** [CodeForPoznan/alinka-electron#72]
TO DO:
* We want to have fourth`Dashboard` view that contains only `Create document` button.
* We want to save created document on some custom location (Save as...)
* That button should be present on the fourth view (summary)

AC:
* After clicking on that button SPECJALNE document should be created.

**Comment by agatakozinska** [comment]
Actually we don't have "the fourth view (summary)" right now :P it was told we don't need this view in this sprint, we just wanted to go through all the steps and create a document
