### ISSUE TITLE
Add database to our project

### ISSUE THREAD

**Issue by Rafalkufel** [CodeForPoznan/alinka-electron#78]
Business context:
We need to store data of:
* students,
* specialists
* schools
* Applications

For that reason we need some database.
In my opinion the best would be some of SQL dbase, Please consider: https://bookshelfjs.org

**Comment by agatakozinska** [comment]
As far as I know @Pragaa was working on db and it wasn't related to SQL in any way :P

**Comment by Rafalkufel** [comment]
Ok. SQL was only my proposition.
