### ISSUE TITLE
Create components from buttons in DocumentForm

### ISSUE THREAD

**Issue by agatakozinska** [CodeForPoznan/alinka-electron#83]
Right now the have just simple html <button> "Back", "Next" and "Create a document" inside DocumentForm. 
Need to change it to React components

Design:
https://www.figma.com/file/eggpYIDsUJya3rgOcXqyuC05/Alinka-design?node-id=2%3A1

AC:
- Buttons in app are React's component, not pure HTML
- Button component are adjusted to style provided in Figma
- Button component has tests
- New component does not break current behavior of app (generating documents, navigating between pages)

**Comment by magul** [comment]
Done in #101
