### ISSUE TITLE
Select for `firstReason`, `secondReason`

### ISSUE THREAD

**Issue by Rafalkufel** [CodeForPoznan/alinka-electron#86]
Two reasons of decission are important only when:
* User chose "Kształcenie specalne"
and
* The chosen first option IS NOT: 
   niedostosowanie społeczne 
   zagrożenie niedostosowaniem społecznym
   stan zdrowia uniemożliwiający uczęszczenie do szkoły
   stan zdrowia znacznie utrudniający uczęszczenie do szkoły

When this this condistoin are not met `secondReason` should be `not visible` or `disabled`.

**Comment by magul** [comment]
Shouldn't that be closed in #119? @Rafalkufel ?

**Comment by Rafalkufel** [comment]
It will be closed after Q&A (hopefuly...) @magul
