### ISSUE TITLE
Installer for Alinka

### ISSUE THREAD

**Issue by Rafalkufel** [CodeForPoznan/alinka-electron#88]
Currently we have some installer, but we want to check if it works with React. 
Ticket is related only to windows. NSIS

**Comment by Maciek246** [comment]
For now available are installers for Windows (NSIS) and Ubuntu (deb). For macOS I will create a dedicated ticket.

**Comment by magul** [comment]
Closing that one as it clearly says that it's limited to Windows/NSIS and it was delivered in #100
