### ISSUE TITLE
Application is not working on Windows OS

### ISSUE THREAD

**Issue by ewelina-m** [CodeForPoznan/alinka-electron#99]
**Description**: I was trying to start application by command: npm start and it ends errors
**Severity:** critical
**Priority:** high 
**Environment:** Windows 10 (64-bit)
**Expected results:** Alinka works on different Windows OS
**Actual results:** Alinka is not working on Windows OS

![2019-11-20_Alinka_Windows](https://user-images.githubusercontent.com/44342935/69267411-5fb32a80-0bcd-11ea-9ff9-5fb65207568a.png)

**Comment by Maciek246** [comment]
I put a link to something that could be helpful for assigned dev: https://www.npmjs.com/package/cross-env
